---
# tasks file for certificate-maker

- name: Check vars
  assert:
    that:
      - path_cert is defined
      - cert_valid_days is defined
      - ca_country is defined
      - ca_organization_name is defined
      - ca_common_name is defined
      - cert_country is defined
      - cert_organization_name is defined
      - cert_common_name is defined
    fail_msg: "Check required variables"

- name: Install python-cryptography requered to openssl* ansible module
  yum:
    name: python-cryptography
    state: installed

# CA CERTIFICATE
- name: Create Private KEY
  openssl_privatekey:
    path: "{{ path_cert }}/ca.key"
    size: 2048

- name: Create CSR for CA
  openssl_csr:
    path: "{{ path_cert }}/ca.csr"
    privatekey_path: "{{ path_cert }}/ca.key"
    country_name: "{{ ca_country }}"
    organization_name: "{{ ca_organization_name }}"
    common_name: "{{ ca_common_name }}"

- name: Create CA
  openssl_certificate:
    path: "{{ path_cert }}/ca.crt"
    privatekey_path: "{{ path_cert }}/ca.key"
    csr_path: "{{ path_cert }}/ca.csr"
    provider: selfsigned

# SERVER CERTIFICATE
- name: Create KEY for Certificate
  openssl_privatekey:
    path: "{{ path_cert }}/server.key"
    size: "{{ ca_priv_key_bits | default(4096) }}"

- name: Create CSR for Certificate
  openssl_csr:
    path: "{{ path_cert }}/server.csr"
    privatekey_path: "{{ path_cert }}/server.key"
    country_name: "{{ cert_country }}"
    organization_name: "{{ cert_organization_name }}"
    common_name: "{{ cert_common_name }}"

- name: Sign Certificate
  openssl_certificate:
    path: "{{ path_cert }}/server.crt"
    privatekey_path: "{{ path_cert }}/server.key"
    csr_path: "{{ path_cert }}/server.csr"
    provider: ownca
    ownca_path: "{{ path_cert }}/ca.crt"
    ownca_privatekey_path: "{{ path_cert }}/ca.key"
    selfsigned_not_after: "+{{ cert_valid_days }}d"
