---
language: python
python: "3.7"

services:
  - docker

sudo: false

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible==2.9.8 molecule==3.0.4 molecule[docker] docker ansible-lint
  - ansible --version
  - ansible-galaxy install -r roles/requirements.yml
  - cp vars/digitalocean.yml.sample vars/digitalocean.yml

script:
  - ansible-playbook -i inventory.do playbooks/site.yml --syntax-check
  - ansible-lint playbooks/
  - ansible-lint roles/
  - cd roles/docker-configuration ; molecule test && cd - || exit 1
