---
language: python
python: "2.7"

services:
  - docker

sudo: false

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible molecule molecule[docker] docker ansible-lint
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - ansible-galaxy install -r roles/requirements.yml

script:
  - ansible-playbook -i inventory.do playbooks/site.yml --syntax-check
  - ansible-lint playbooks/
  - ansible-lint roles/
