---
language: python
python: "2.7"

services:
  - docker

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install ansible molecule molecule[docker] docker

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - cd roles/certificate-maker ; molecule test && cd - || exit 1
  - cd roles/docker-configuration ; molecule test && cd - || exit 1
  #  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
