---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: instance
    image: milcom/centos7-systemd
    pre_build_image: true
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible
