---
# tasks file for docker-swarm
- name: set fact
  set_fact:
    first_master_ip: "{{ hostvars[groups['docker'][0]]['ansible_default_ipv4']['address'].split('\n')[0] }}"

- name: init a new swarm
  delegate_to: "{{ first_master_ip }}"
  run_once: true
  block:
    - name: init swarm
      docker_swarm:
        state: present
        advertise_addr: "{{ first_master_ip }}"

    - name: get join token for manager
      shell: docker swarm join-token manager
      register: _manager_token

    - name: get join token for worker
      shell: docker swarm join-token worker
      register: _worker_token

- name: set advertise addr
  set_fact:
    manager_join_cmd: "{{ _manager_token.stdout_lines[2] }}"
    worker_join_cmd: "{{ _worker_token.stdout_lines[2] }}"

- name: get docker swarm info
  docker_swarm_info:
  ignore_errors: true
  register: _swarm

- name: join nodes
  when: _swarm.failed
  shell: "{{ manager_join_cmd }}"
