---
# tasks file for docker-configuration

- name: ensure systemd docker directory exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: copy template
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
  register: _template

- name: restart docker
  when: _template.changed
  systemd:
    name: docker
    daemon_reload: true
    state: restarted
    enabled: true
