---
# tasks file for docker-configuration

- name: ensure systemd docker directory exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: copy template
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
  notify:
    - restart docker
