---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        path_cert: /tmp/
        ca_country: IT
        ca_organization_name: example
        ca_common_name: example.com
        cert_country: IT
        cert_organization_name: examplelab
        cert_common_name: docker

verifier:
  name: ansible
